apiVersion: v1
kind: Secret
metadata:
  name: zava-secrets
  namespace: zava
type: Opaque
stringData:
  APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=fb0c6937-667b-4f41-a095-202665d3be85;IngestionEndpoint=https://swedencentral-0.in.applicationinsights.azure.com/;LiveEndpoint=https://swedencentral.livediagnostics.monitor.azure.com/;ApplicationId=f100d164-eec5-459a-93e0-e85c67408895"
